<a href="https://colab.research.google.com/github/Nagendra-Bankupalli/day4_example/blob/main/Copy_of_indexing_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Accessing elements in a tensor

'''
tensor [ row, column]
'''
import torch

In [4]:
tensor = torch.tensor([
                      [10,20,30],
                      [40,50,60],
                      [70,80,90]
                      ])

print(tensor.ndim) # print num of dimensions
print(tensor.shape) # print shape



2
torch.Size([3, 3])


In [5]:
print("elemtn at (0,1)", tensor[0,1])

elemtn at (0,1) tensor(20)


In [6]:
tensor[0] # complete row, first row

tensor([10, 20, 30])

In [7]:
tensor[:, 0] # first column

tensor([10, 40, 70])

In [9]:
# slicing

print("first two rows \n ", tensor[:2])  # get first two rows

first two rows 
  tensor([[10, 20, 30],
        [40, 50, 60]])


In [10]:
# first two columns

print("first two columns \n", tensor[:, :2])

first two columns 
 tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [11]:
# print main matrix all rws  and columns
print(tensor)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [14]:
#
print(tensor[1, 1:3])  # row-1 , column 1 to 2 only

tensor([50, 60])


In [18]:
# access specific value , fancy indexing
# (0,1) -> 20
# (2,2) -> 90
tensor[[0,2], [1,2]]

tensor([20, 90])

In [20]:
# boolean indexing , elments > mask => true else false

mask = tensor > 50

print(mask)

print(tensor[mask])  # will print elemtns > 50

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [21]:
# chane/update the tensor values using index
print(tensor)
tensor[0,1] = 25
print(tensor)


tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [24]:
tensor[:,0] = torch.tensor([100,200,300])
print(tensor)

tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [26]:
indices = torch.tensor([0,2])
selected_rows = torch.index_select(tensor, dim=1, index=indices)
print(selected_rows)


tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [28]:
# using tensor with ssteps

print(tensor[:, ::2])

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [30]:
# flip

torch.flip(tensor,dims=(0,))

tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  25,  30]])