<a href="https://colab.research.google.com/github/Nagendra-Bankupalli/day4_example/blob/main/matrix_aggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
matrix = torch.tensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       ])
print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [3]:
print(matrix.sum())

tensor(45.)


In [4]:
print(matrix.min())
print(matrix.max())
print(matrix.mean())


tensor(1.)
tensor(9.)
tensor(5.)


In [5]:
# dim=0 --> rows (across columns)
# dim=1 --> columns (across rows)

print(matrix.sum(dim=0))
print(matrix.min(dim=0))
print(matrix.max(dim=1))
print(matrix.mean(dim=0))

tensor([12., 15., 18.])
torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))
torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))
tensor([4., 5., 6.])


In [6]:
# cumulative sum

cum_sum = matrix.cumsum(dim=1)
print(cum_sum)

tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.],
        [ 7., 15., 24.]])


In [8]:
# cumulative product
cum_pro = matrix.cumprod(dim=0)
print(cum_pro)


tensor([[  1.,   2.,   3.],
        [  4.,  10.,  18.],
        [ 28.,  80., 162.]])


In [11]:
# advance aggregation

masked_matrix_sum = matrix[matrix>8].sum()
print(masked_matrix_sum)

tensor(9.)


In [15]:
matrix = torch.tensor([[0.,0.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       ])

non_zero = matrix.nonzero()
print(non_zero)
print(non_zero.shape)
print(non_zero.size(0))

tensor([[0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])
torch.Size([7, 2])
7


In [16]:
# normalize matrix

matrix = torch.tensor([[0.,0.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       ])

max_v = matrix.max()
min_v = matrix.min()
normalized_matrix = (matrix - min_v) / (max_v - min_v)

print(normalized_matrix)


tensor([[0.0000, 0.0000, 0.3333],
        [0.4444, 0.5556, 0.6667],
        [0.7778, 0.8889, 1.0000]])
