<a href="https://colab.research.google.com/github/Nagendra-Bankupalli/day4_example/blob/main/stackOeration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [2]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])


In [3]:
print(tensor_1.ndim)
print(tensor_1.size())

1
torch.Size([3])


In [7]:
stack_tensor_dim_0 = torch.stack((tensor_1,tensor_2), dim=0)  # stack on row
print("shape :", stack_tensor_dim_0)
print(stack_tensor_dim_0.shape)
print( " ")
stack_tensor_dim_1 = torch.stack((tensor_1, tensor_2), dim=1)  # stack on column
print("shape :", stack_tensor_dim_1)
print(stack_tensor_dim_1.shape)

shape : tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
 
shape : tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


In [8]:
 # more tensor stack up
tensor_3 = torch.tensor([7,8,9])
stack_tensor_dim_0_new = torch.stack((tensor_1,tensor_2,tensor_3), dim=0)  # stack on row
print("shape :", stack_tensor_dim_0_new)
print(stack_tensor_dim_0_new.shape)

shape : tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [12]:
# stacking 2D tensors using stack function in dim=0

tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])

stacked_tensor_2d = torch.stack((tensor1,tensor2), dim=0)
print("shape :", stacked_tensor_2d.shape)
print(stacked_tensor_2d)
print(stacked_tensor_2d.ndim)



shape : torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3


In [17]:
# stacking 2D tensors using stack function in dim=1



stacked_tensor_2d_d1 = torch.stack((tensor1,tensor2), dim=1)
print("shape :", stacked_tensor_2d_d1.shape)
print(stacked_tensor_2d_d1)
print(stacked_tensor_2d_d1.ndim)

shape : torch.Size([2, 2, 2])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
3


In [20]:
# stacking 2D tensors using stack function in dim=2


print(tensor1)
print(tensor2)

stacked_tensor_2d_d2 = torch.stack((tensor1,tensor2), dim=2)
print("shape :", stacked_tensor_2d_d2.shape)
print(stacked_tensor_2d_d2)
print(stacked_tensor_2d_d2.ndim)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
shape : torch.Size([2, 2, 2])
tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])
3


In [21]:
# [1,2]   ==> dim0 = [1,2], dim1 = 1
# [[1,2]] ==> dim0 = [1,2], dim1 = 1,2 dim2 = 1, and 2

In [23]:
## Concatnation operation , no change in dimension

concatnated_tensor = torch.cat((tensor1,tensor2),dim=0)

print("shape ", concatnated_tensor.shape)
print(concatnated_tensor)
print(concatnated_tensor.ndim)

shape  torch.Size([4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
2


In [24]:
concatnated_tensor = torch.cat((tensor1,tensor2),dim=1)

print("shape ", concatnated_tensor.shape)
print(concatnated_tensor)
print(concatnated_tensor.ndim)

shape  torch.Size([2, 4])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
2
