<a href="https://colab.research.google.com/github/Nagendra-Bankupalli/day4_example/blob/main/tensor_data_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
# data types of tensors

'''
floating - for  most deep learning tasks -> float32, float64 , forat16
integers - for categorical data and indicies -> int32, int64, int8
boolean - mask or logical operations / true/false
complex number - advanced computation -> complex64, complex128

memory consumption : float16 << float32 << float64
computation : lower prcision will be faster on GPU
numerical precision : flaot64 is more precise than float32

'''



'\nfloating - for  most deep learning tasks -> float32, float64 , forat16 \nintegers - for categorical data and indicies -> int32, int64, int8 \nboolean - mask or logical operations / true/false \ncomplex number - advanced computation -> complex64, complex128 \n\nmemory consumption : float16 << float32 << float64\ncomputation : lower prcision will be faster on GPU\nnumerical precision : flaot64 is more precise than float32\n\n'

In [5]:
default_tensor = torch.tensor([1.5,2.5,3.5])
print(default_tensor.dtype)

torch.float32


In [6]:
float_tensor = torch.tensor([1.5,2.5,3.5], dtype=torch.float64)
print(float_tensor.dtype)

torch.float64


In [8]:
int32_tensor = torch.tensor([1.5,2.5,3.5], dtype=torch.int32)
print(int32_tensor.dtype)
print(int32_tensor)

torch.int32
tensor([1, 2, 3], dtype=torch.int32)


In [9]:
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)
print(bool_tensor.dtype)
print(bool_tensor)

torch.bool
tensor([ True, False,  True])


In [11]:
# convert to int tensor from float

float_tensor  = torch.tensor([1.5,2.5,3.5])
print(float_tensor.dtype)
print(float_tensor)
print(" ")
int_tensor = float_tensor.to(torch.int64)
print(int_tensor)
print(int_tensor.dtype)



torch.float32
tensor([1.5000, 2.5000, 3.5000])
 
tensor([1, 2, 3])
torch.int64


In [14]:
## impact of datatype on memory

float32_tensor = torch.ones(1000, dtype=torch.float32)
float64_tensor = torch.ones(1000, dtype=torch.float64)

# tensor.element_size() => size of one element size in bytes
# element_size()
# nelement - number of elemetns

print(float32_tensor.element_size())
print(float32_tensor.nelement())
print("memory used by float32 tensor ", float32_tensor.element_size() * float32_tensor.nelement())
print(" ")
print(float64_tensor.element_size())
print(float64_tensor.nelement())
print("memory used by float64 tensor ", float64_tensor.element_size() * float64_tensor.nelement())

4
1000
memory used by float32 tensor  4000
 
8
1000
memory used by float64 tensor  8000


In [ ]:
# float32 --> default for most NN models
# float64 --> high precision computation
# int32 --> general purpose integer
# int64 --> tensor undices
# int8 & int16 --> reduce memory usage
# bool --> mask and logical operations
# float16 --> half precision of default folat type , redude memory usage
# complex64 --> advanced computation
