<a href="https://colab.research.google.com/github/Nagendra-Bankupalli/day4_example/blob/main/tensor_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# tensor manipulation
'''
- reshaping
- slicing
- joining or splitting
- transposing and permuting dimension
'''

'\n- reshaping \n- slicing \n- joining or splitting \n- transposing and permuting dimension\n'

In [3]:

import torch



In [4]:
# reshaping

# reshape
# view

original_tensor = torch.arange(12)
print(original_tensor)
print(original_tensor.nelement())
print(original_tensor.ndim)



tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


In [5]:
# change this vector to 2x6 matrix
# 2x6 --> 12

reshaped_tensor = original_tensor.reshape(3,4)
print(reshaped_tensor)
print(reshaped_tensor.nelement())
print(reshaped_tensor.ndim)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
12
2


In [6]:
# view
print(original_tensor.is_contiguous())
flatternd_tensor = original_tensor.view(-1)
print(flatternd_tensor)


True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [9]:
# slicing - extract specific portin of tensor

tensor_a = torch.tensor([[1,2,3], [4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.ndim)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2


In [10]:
print(tensor_a[0])

tensor([1, 2, 3])


In [14]:
tensor_a[:,2]  # first column

tensor([3, 6, 9])

In [15]:
print(tensor_a.shape)

torch.Size([3, 3])


In [19]:
# extract 2x2 from this 3x3 tensor

sub_tensor = tensor_a[1:, 1:]
print(sub_tensor)
print(sub_tensor.shape)

tensor([[5, 6],
        [8, 9]])
torch.Size([2, 2])


In [22]:
# joining Tensors
# torch.cat() =--> merges tesnsors along an existing dimension

tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])

print(tensor1)
print(tensor2)

print("**"*8)

concat_tensr_r = torch.cat((tensor1,tensor2), dim=0)
concat_tensr_c = torch.cat((tensor1,tensor2), dim=1)

print(concat_tensr_r)
print(concat_tensr_r.shape)
print(concat_tensr_c)
print(concat_tensr_c.shape)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
****************
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
torch.Size([2, 4])


In [23]:
# stack --> creates new dimension , increases the ternsor Rank

print(tensor1.shape)
print(tensor2.shape)

print("**"*8)

concat_tensr_r = torch.stack((tensor1,tensor2), dim=0)
concat_tensr_c = torch.stack((tensor1,tensor2), dim=1)

print(concat_tensr_r)
print(concat_tensr_r.shape)
print(concat_tensr_c)
print(concat_tensr_c.shape)


torch.Size([2, 2])
torch.Size([2, 2])
****************
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
torch.Size([2, 2, 2])


In [25]:
# split tensors

# - torch.chunk() ---> divides your tensor into equal sized chunks
# - torch.split() ---> allows eneven splitting based on size

# torch.chunk()

ori_tensor = torch.arange(12)

chunks  = torch.chunk(ori_tensor, 5, dim=0)

print(chunks)

for chunk in chunks:
  print(chunk)



(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [27]:
# torch.split()

split  = torch.split(ori_tensor, 7, dim=0)

print(split)

for sp in split:
  print(sp)

(tensor([0, 1, 2, 3, 4, 5, 6]), tensor([ 7,  8,  9, 10, 11]))
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([ 7,  8,  9, 10, 11])


In [28]:
# transposing and permuting

# transpose() --> swaps two dimensions --> nxm -> mxn

# permute() --> rearrange all dimensions in the specified order

tensor_org = torch.arange(24).reshape(12,2)

transposed_tensor = tensor_org.transpose(0,1)

print(tensor_org)
print(transposed_tensor)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])


In [32]:
# permute
tensor_ori = torch.arange(24).reshape(2, 3, 4)

print(tensor_ori)
print(tensor_ori.shape)
print("**"*7)

# [0,1,2]
permuted_tensor = tensor_ori.permute(2,0,1) # [2,3,4] changed to [4,2,3]
print(permuted_tensor)
print(permuted_tensor.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
**************
tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])
torch.Size([4, 2, 3])


In [33]:
# cloning and detaching

import copy

a = [1,2,3]

b = copy.deepcopy(a)

print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [ ]:
tensor = torch.ones(3,3, requires_grad=True) # part of computation graph

cloned_tensor = tensor.clone() # part of computation graph

detached_tensor = tensor.detach() # this code will detach tensor  from computation graph
