<a href="https://colab.research.google.com/github/Nagendra-Bankupalli/day4_example/blob/main/view_and_reshape_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
tensor = torch.arange(12)

reshaped_tensor_view = tensor.view(2,6)
reshaped_tensor_reshape = tensor.reshape(2,6)

print(reshaped_tensor_view)
print(reshaped_tensor_reshape)

print(reshaped_tensor_reshape.shape)


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])


In [4]:
tensor.is_contiguous()

True

In [6]:
infered_shape = tensor.view(3, -1)
print(infered_shape)
print(infered_shape.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [7]:
tensor3d = torch.arange(24).reshape(2,3,4)
print(tensor3d)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [9]:
flatt = tensor3d.view(-1)
print(flatt)
print(flatt.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
torch.Size([24])


In [10]:
flatt.is_contiguous()

True

In [11]:
tensor2d = torch.arange(24).reshape(12,2)
print(tensor2d)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])


In [12]:
tranpose_tensor = tensor2d.t()
tranpose_tensor.is_contiguous()

False

In [14]:
err = tranpose_tensor.reshape(6,4)
print(err)
print(err.shape)


tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])
